# Generated by Django 4.2 on 2023-04-17 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid mobile number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
